language: node_js
addons:
  apt:
    packages:
      - libgconf-2-4

cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/.cache

notifications:
  email: false

node_js:
  - '15.7.0'

install:
  - yarn

before_script:
  - yarn

script:
  - yarn lint
  - yarn test
